### PR TITLE
Failure in running the elastic_beanstalk_enhanced_health_reporting_enabled query closes #269

### LINKED ISSUE #269: Failure in running the elastic_beanstalk_enhanced_health_reporting_enabled query
**Describe the bug**
While running the `elastic_beanstalk_enhanced_health_reporting_enabled` query we are getting an error like this - 
```
Error: failed to create prepared statement for query.elastic_beanstalk_enhanced_health_reporting_enabled: pq: argument of CASE/WHEN must be type boolean, not type text
```

**Steampipe version (`steampipe -v`)**
Example: v0.7.3

**Plugin version (`steampipe plugin list`)**
Example: v0.12

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by misraved**
### Checklist
- [ ] Issue(s) linked

### CODE REVIEW

File: query/elasticbeanstalk/elastic_beanstalk_enhanced_health_reporting_enabled.sql [hunk 1]
```diff
@@ -2,11 +2,15 @@ select
   -- Required Columns
   application_name as resource,
   case
-    when health_status then 'ok'
+    when health_status is not null and
```
Comment (rajlearner17) [inline query/elasticbeanstalk/elastic_beanstalk_enhanced_health_reporting_enabled.sql:5]: when health_status is not null and health is not null then 'ok'

**Review by rajlearner17 — APPROVED** [review]
LGTM
