### PR TITLE
ebs_attached_volume_encryption_enabled should validate all EBS volume without where condition Closes #503

### LINKED ISSUE #503: ebs_attached_volume_encryption_enabled should validate all EBS volume without where condition
**Describe the bug**

[Reference](https://hub.steampipe.io/mods/turbot/aws_compliance/queries/ebs_attached_volume_encryption_enabled) 

we should check all volumes without `where` condition

```
 select
  -- Required Columns
  arn as resource,
  case
    when encrypted and state = 'in-use' then 'ok'
    when encrypted then 'info'
    else 'alarm'
  end as status,
  case
    when encrypted and state = 'in-use' then volume_id || ' attached and encrypted.'
    when encrypted then volume_id || ' encrypted, not attached.'
    else volume_id || ' not encrypted.'
  end as reason,
  -- Additional Dimensions
  region,
  account_id
from
  aws_ebs_volume
```

image

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by khushboo9024**
### Checklist
- [ ] Issue(s) linked

### CODE REVIEW

File: query/ebs/ebs_attached_volume_encryption_enabled.sql [hunk 1]
```diff
@@ -2,17 +2,17 @@ select
   -- Required Columns
   arn as resource,
   case
+    when state != 'in-use' then 'info'
```
Comment (cbruno10) [inline query/ebs/ebs_attached_volume_encryption_enabled.sql:5]:
```suggestion
    when state != 'in-use' then 'skip'
```

If we're not evaluating them, should it be in `skip` state instead? What does the original query/config rule say about evaluating unattached volumes (or doesn't say)?

**Review by cbruno10 — CHANGES_REQUESTED** [review]
@khushboo9024 Please see comment, thanks!

File: query/ebs/ebs_attached_volume_encryption_enabled.sql (hunk 1 above)
Comment (rajlearner17) [reply query/ebs/ebs_attached_volume_encryption_enabled.sql:5]: @cbruno10 this is what it says below; non-attached ones we can `skip`

```
This control checks whether the EBS volumes that are in an attached state are encrypted. To pass this check, EBS volumes must be in use and encrypted. If the EBS volume is not attached, then it is not subject to this check.
```

**Review by misraved — APPROVED** [review]
